# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"rename_duplicates": "00_mldsutils.ipynb",
         "run_classifiers": "00_mldsutils.ipynb",
         "plot_bars": "00_mldsutils.ipynb",
         "run_regressors": "00_mldsutils.ipynb",
         "plot_decision_boundaries": "01_plots.ipynb"}

modules = ["mldsutils.py"]

doc_url = "https://tirthajyoti.github.io/mldsutils/"

git_url = "https://github.com/tirthajyoti/mldsutils/tree/master/"

def custom_doc_links(name): return None
